name: Custom Workflow

on: 
  pull_request:
    types: [closed]
    
jobs:
  build:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Check PR body
      id: check
      run: |
          body=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json body -q '.body')
          if [[ -n "$body" ]]; then
            echo "The PR body is not empty."
            echo "::set-output name=trigger::true"
          else
            echo "The PR body is empty."
            echo "::set-output name=trigger::false"
          fi
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Conditional step
      if: steps.check.outputs.trigger == 'true'
      run: echo "Running the next steps..."
