name: Custom Workflow

on: 
  pull_request:
    types: [closed]
    
jobs:
  build:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Check PR body
      run: |
        PR_BODY="${{ github.event.pull_request.body }}"
        if [[ "$PR_BODY" == "true" ]]; then
          echo "PR body is 'true'. Proceeding with the workflow."
        else
          echo "PR body is not 'true'. Failing the workflow."
          exit 1
        fi
