name: Custom Workflow

on: 
  pull_request:
    types: [closed]
    
jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check PR body
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          if [[ -z "$PR_BODY" ]]; then
            echo "PR body is empty. Failing the workflow."
            exit 1
          else
            echo "PR body is not empty. Proceeding with the workflow."
            echo "Input Text is - $PR_BODY"
          fi	  
