name: Custom Workflow

on: 
  pull_request:
    types: [closed]
    
jobs:
  build:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Extract PR body
      id: extract_body
      run: echo "::set-output name=body::${{ github.event.pull_request.body }}"
      
    - name: Display PR body
      run: echo "PR Body: ${{ steps.extract_body.outputs.body }}"
