name: Custom Workflow

on: 
  pull_request:
    types: [closed]
    
jobs:
  build:
    name: excute-test-cases
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Check PR body
      id: check
      run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          if [[ -n "$PR_BODY" ]]; then
            echo "PR body contains text."
            echo "PR Body: $PR_BODY"
        
